#!/bin/bash

#
# This script starts IPC server, account generator, etc.
#

if [ $EUID == 0 ]; then
    echo "This script must not be run as root"
    exit
fi

if ! [ -d "./user_instances" ]; then
    echo "You need to run install-catbots first."
    exit
fi

# Check if system is Debian-based
if [ -f "/etc/debian_version" ]; then
    echo "export PATH=$PATH:/sbin" >> .bashrc
    source .bashrc
fi

sudo mkdir -p /opt/steamapps
mountpoint -q /opt/steamapps || sudo mount --bind ~/.steam/steam/steamapps/ /opt/steamapps

screen -S ipc -d -m /opt/cathook/ipc/bin/server
echo $! >/tmp/cat-ipc-server.pid

if [ -e "/tmp/ncat-cathook-webpanel.pid" ] && ps -p `cat "/tmp/ncat-cathook-webpanel.pid"` >/dev/null; then
    echo IPC panel already running.
else
    pushd catbot-ipc-web-panel
    sudo PATH="$PATH" STEAM_LD_PRELOAD="$(cd ../ && pwd)/just-disable-vac/build/bin64/libvpcfs.so.0:$(cd ../ && pwd)/just-disable-vac/build/bin32/libvpcfs.so.0" bash ./run.sh &
    popd
fi

echo "⠀⠀⠀⠀⠀⠀⠀⠀⢠⣴⣶⣿⣿⣿⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⡿⠿⣿⣻⣧⡀⣠⣦⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⢠⠟⠹⠷⢸⠛⢹⣿⢣⣺⢿⣿⣿⡆⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⢀⠔⠈⠄⠀⢘⣐⢁⢀⢟⢼⣿⡋⠙⠻⡇⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⣠⢣⡀⢠⠀⣑⢌⠋⠉⠟⣭⡿⢅⠔⡉⢃⠻⡆⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⢸⢃⠂⢱⠚⠤⢠⠱⠅⠨⢴⡇⠰⠂⠠⠈⠄⢂⢣⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠌⢸⠆⠈⠀⠀⠸⠐⣄⢀⣾⣶⣎⠢⢄⠊⠈⠊⠀⡆⠀⠀⠀⠀⠀⠀
⠀⠀⠀⡎⠀⠀⢻⡤⠀⠸⣷⣿⣾⢑⣸⠁⠀⠀⠀⠈⠤⢀⡰⠃⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠐⠄⠤⠊⠀⠀⠀⠸⠀⠈⠈⠀⠀⠀⠀⠀⠀⢀⠇⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣆⡀⠀⠀⠀⠠⠄⣀⡴⠾⠤⠀⡀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⡀⠄⠊⢬⣋⠛⢏⡉⠉⢉⣿⣿⠞⣒⣶⣤⣤⣀⣠⡀⠀⠀⠀
⠀⠀⠀⢀⠠⣂⣵⣶⣿⣿⣿⣿⣿⣦⣄⠀⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣮⣂⠀⠀
⠀⢀⣴⣷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣿⣿⣿⠿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀
⠀⢸⣿⣧⣿⣿⣿⣿⣿⡿⠟⠋⠉⠉⠁⠀⠀⠀⠀⠀⠀⢨⣿⣿⣿⣿⣿⡇⠀⠀
⠀⠈⢿⣿⣿⣿⣿⣿⡁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣷⣿⣿⣿⣿⣿⣇⠀⠀
⠀⠀⣾⣿⣿⣿⣿⣿⡷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠻⠿⠿⠿⡿⠿⠀⠀
⠀⠀⠙⠻⠛⠋⠉⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠂⠀⠀⠀
⠀⠀⠀⠀⠆⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡆⠀⠘⠀⠀⠀⠀
⠀⠀⠀⠀⢠⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⡇⠀⠀⠀⠀
⠀⠀⠀⢀⣸⡄⠘⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠃⢀⣇⠀⠀⠀⠀
⣀⣠⣶⣿⡿⢿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣶⣾⡿⣷⡄⡀⠀
⠙⠛⠛⠛⠛⠉⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠛⠻⣾⣿⣿⠶⠿"
echo "lets own some legits"
sleep 2;

clear;

if [ -x "$(command -v pulseaudio)" ]; then
    echo "Setting up micspam..."
    pulse=$(pgrep -u "$USER" pulseaudio);
    ([ ! -z "$pulse" ]) && pulseaudio --start &>/dev/null &
    pactl load-module module-native-protocol-unix auth-anonymous=1 socket=/tmp/pulse.sock > /tmp/pulsemodule.id
fi

Xvfb :1 -screen 0 640x200x24 +extension GLX -maxclients 2048 & >/dev/null

sleep 5;

echo "IPC Web Panel password: `cat /tmp/cat-webpanel-password`"
sudo chmod 700 /opt/steamapps/common/Team\ Fortress\ 2/tf/glshaders.cfg

echo "Open a web browser and go to localhost:7655 to see your catbot IPC web panel."
echo "If u wanna connect to panel with other internet, just forward port."
echo "Mistakes Multiplied 2025"
